on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: main
jobs:
  macos:
    name: 'MacOS (x64)'
    runs-on: macos-11

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: ./install.dependencies.sh
      working-directory: build/macos-x64

    - name: Clone ImageMagick libraries
      run: ./checkout.sh macos ../../../artifacts
      working-directory: src/ImageMagick

    - name: Build libraries
      run: ../../../build/macos-x64/build.libraries.sh ../../../build/libraries
      working-directory: src/ImageMagick/libraries

    - name: Build ImageMagick
      run: ../../../build/shared/build.ImageMagick.sh macos x64
      working-directory: src/ImageMagick/libraries

    - name: Build Native
      run: ../../build/shared/build.Native.sh macos x64
      working-directory: src/Magick.Native

    - name: Copy Native
      run: ../../build/shared/copy.Native.sh macos x64 ../../artifacts
      working-directory: src/Magick.Native

    - name: Upload library
      uses: actions/upload-artifact@v3
      with:
        name: macos-x64
        path: artifacts

  macos_arm64:
    name: 'MacOS (arm64)'
    runs-on: macos-11

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: ./install.dependencies.sh
      working-directory: build/macos-arm64

    - name: Clone ImageMagick libraries
      run: ./checkout.sh macos ../../../artifacts
      working-directory: src/ImageMagick

    - name: Build libraries
      run: ../../../build/macos-arm64/build.libraries.sh ../../../build/libraries
      working-directory: src/ImageMagick/libraries

    - name: Build ImageMagick
      run: ../../../build/shared/build.ImageMagick.sh macos arm64
      working-directory: src/ImageMagick/libraries

    - name: Build Native
      run: ../../build/shared/build.Native.sh macos arm64
      working-directory: src/Magick.Native

    - name: Copy Native
      run: ../../build/shared/copy.Native.sh macos arm64 ../../artifacts
      working-directory: src/Magick.Native

    - name: Upload library
      uses: actions/upload-artifact@v3
      with:
        name: macos-arm64
        path: artifacts

  verify_macos:
    name: 'Verify MacOS'
    needs:
      - macos
      - macos_arm64
    strategy:
      matrix:
        os: [macos-11, macos-12]
        arch: [x64, arm64]
    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Download macos library
      uses: actions/download-artifact@v3
      with:
        name: macos-${{ matrix.arch }}

    - name: Verify MacOS
      run: build/shared/verify.Native.MacOS.sh macos ${{ matrix.arch }} . 
