on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:

  macos:
    name: 'MacOS (x64)'
    runs-on: macos-11

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: ./install.dependencies.sh
      working-directory: build/macos-x64

    - name: Clone ImageMagick libraries
      run: ./checkout.sh macos ../../../artifacts
      working-directory: src/ImageMagick

    - name: Build libraries
      run: ../../../build/macos-x64/build.libraries.sh ../../../build/libraries
      working-directory: src/ImageMagick/libraries

  macos_arm64:
    name: 'MacOS (arm64)'
    runs-on: macos-11

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: ./install.dependencies.sh
      working-directory: build/macos-arm64

    - name: Clone ImageMagick libraries
      run: ./checkout.sh macos ../../../artifacts
      working-directory: src/ImageMagick

    - name: Build libraries
      run: ../../../build/macos-arm64/build.libraries.sh ../../../build/libraries
      working-directory: src/ImageMagick/libraries

